services:
  server:
    image: feathers-mmo-admin-tools-server
    build: server
    volumes:
      - './server:/home/node/app'
    ports:
      - 3030:3030
      - 9229:9229
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
  adminer:
    image: adminer
    ports:
      - 8080:8080
